# Generated by Django 4.0.4 on 2022-05-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_searchq_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchq',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
