# Generated by Django 4.0.4 on 2022-05-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_searchq_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200)),
                ('question', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(null=True)),
                ('is_positive', models.BooleanField()),
            ],
        ),
    ]
