# Generated by Django 4.0.4 on 2022-05-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_traindata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantVars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var', models.DateField()),
            ],
        ),
    ]
