# Generated by Django 4.0.4 on 2022-05-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_importantvars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importantvars',
            old_name='var',
            new_name='date',
        ),
        migrations.AddField(
            model_name='importantvars',
            name='purpose',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
