# Generated by Django 4.0.4 on 2022-06-01 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_rename_var_importantvars_date_importantvars_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='traindata',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
