# Generated by Django 4.0.4 on 2022-06-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_traindata_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traindata',
            old_name='query',
            new_name='post_title',
        ),
        migrations.RemoveField(
            model_name='traindata',
            name='is_positive',
        ),
        migrations.RemoveField(
            model_name='traindata',
            name='question',
        ),
        migrations.AddField(
            model_name='traindata',
            name='positive_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='traindata',
            name='times_answered',
            field=models.IntegerField(null=True),
        ),
    ]
