# Generated by Django 4.0.4 on 2022-06-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_query_traindata_post_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traindata',
            name='user',
        ),
        migrations.AddField(
            model_name='traindata',
            name='ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
