# Generated by Django 4.0.4 on 2022-06-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_trainips_remove_traindata_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traindata',
            name='author',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='traindata',
            name='subreddit',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
