# Generated by Django 4.0.4 on 2022-06-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_traindata_author_alter_traindata_subreddit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traindata',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='traindata',
            name='subreddit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
