# Generated by Django 4.0.4 on 2022-06-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_traindata_author_alter_traindata_subreddit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='searchq',
            name='most_negative',
            field=models.ManyToManyField(related_name='most_negative', to='main.sentence'),
        ),
        migrations.AddField(
            model_name='searchq',
            name='most_positive',
            field=models.ManyToManyField(related_name='most_positive', to='main.sentence'),
        ),
    ]
