# Generated by Django 4.0.4 on 2022-06-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_sentence_searchq_most_negative_searchq_most_positive'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='sentence_score',
            field=models.FloatField(null=True),
        ),
    ]
