# Generated by Django 4.0.4 on 2022-06-28 19:04

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_traindata_post_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classifiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classifier', picklefield.fields.PickledObjectField(editable=False)),
                ('classifier_date', models.DateField()),
            ],
        ),
    ]
