# Generated by Django 4.0.4 on 2022-06-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_classifier_classifier_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='importantvars',
            name='value',
            field=models.IntegerField(null=True),
        ),
    ]
