# Generated by Django 4.0.4 on 2022-07-15 08:35

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_importantvars_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='top_100',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_obj', picklefield.fields.PickledObjectField(editable=False, null=True)),
                ('top_date', models.DateField()),
                ('top_pos_neg', models.CharField(max_length=3)),
            ],
        ),
    ]
